server:
  port: 8001

  #Undertow配置
#  undertow:
#    threads:
#      io: 20 #设置IO线程数
#      worker: 200 #设置Worker线程数
#    buffer-size: 1024 #设置缓冲器大小
#    direct-buffers: true #开启直接内存分配

#Spring Boot Actuator 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"  #开放所有监控Endpoint
  endpoint:
    health:
      show-details: always  #展示Endpoint明细

spring:
  application:
    name: customer-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # MyBatis-Plus数据源配置
  datasource:
    dynamic: #实现动态数据源
      primary: master
      druid:
        initial-size: 3
        min-idle: 3
        max-active: 40
        max-wait: 60000
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/customer_system?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 12345678
        beijing:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/customer_beijing?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 12345678
        shanghai:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/customer_beijing?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 12345678
        hangzhou:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/customer_beijing?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 12345678
mybatis-plus:
  mapper-locations: classpath:mapperXml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # MyBatis-Plus 全局配置
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: is_deleted
      # 逻辑删除字面值：未删除为0
      logic-not-delete-value: 0
      # 逻辑删除字面值：删除为1
      logic-delete-value: 1

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: customer-system
      logpath: /tmp/xxl-job-executor/logs
      logretentiondays: 30

---
#指定Admin Server地址,进行监控指标上报
spring:
  boot:
    admin:
      client:
        url: http://localhost:9000
